#!name=duolingo

#!desc=duo

#!author=yazar



^https?:\/\/(?:[a-zA-Z0-9-]+\.)?duolingo\.[^\/]+\/\d{4}-\d{2}-\d{2}\/batch\/ url script-request-header https://raw.githubusercontent.com/circas/duoo/refs/heads/main/duo.js
^https?:\/\/(?:[a-zA-Z0-9-]+\.)?duolingo\.[^\/]+\/\d{4}-\d{2}-\d{2}\/batch\/ url script-response-body https://raw.githubusercontent.com/circas/duoo/refs/heads/main/duo.js




hostname = ios-api-cf.duolingo.com
