#!name=duolingo

#!desc=duo

#!author=yazar



^https://ios-api-cf.duolingo.com/2023-05-23/batch url script-request-header https://raw.githubusercontent.com/circas/duoo/refs/heads/main/duo.js
^https://ios-api-cf.duolingo.com/2023-05-23/batch url script-response-body https://raw.githubusercontent.com/circas/duoo/refs/heads/main/duo.js




hostname = ios-api-cf.duolingo.com
